//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrollAjax
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public Nullable<int> FK_CountryId { get; set; }
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
